language: python
python:
    - "3.3"
install:
    - pip install -r ./autotex/requirements.txt
    - pip install -r ./autotex/requirements-dev.txt
script:
    - pylint --rcfile=./autotex/.pylintrc ./autotex/autotex

