language: python
sudo: false
python:
    - "3.4"
install:
    - pip install -U pip
    - cd autotex && pip install -e .[dev] && cd ..
script:
    - flake8 -v .
    - pylint --rcfile=.pylintrc ./autotex/autotex
    - pylint --rcfile=.pylintrc ./unicode/generate.py

